version: "3"

services:
  apoli:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ./apoli:/apoli
    command: >
      sh -c "python manage.py wait_for_db &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:3000"

    environment:
      - DB_HOST=db
      - DB_NAME=apoli
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=apoli
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
